### ISSUE TITLE
Download without watermark

### ISSUE THREAD

**Issue by NapInFever** [Caff1982/LikeeScraper#2]
it would be great if it's to possible to get videos without watermark.

I found another tool that got this implemented

https://github.com/bellingcat/likee-downloader/pull/5

Thank you

**Comment by Caff1982** [comment]
Hi, thanks for raising this issue and I apologise for the delay in my response. I've now changed the code so that the watermarks are removed from the videos (along with some refactoring).

If you have any further problems/suggestions don't hesitate to raise another issue.

Thanks
